# yamllint disable rule:document-start
- id: identity
  name: identity
  description: 'Check git user name and email against list of authors'
  entry: identity
  language: python
  types: [python]
- id: pydocstyle_wrapper
  name: pydocstyle_wrapper
  description: 'Wrapper for the PEP257 checker utility'
  entry: pydocstyle_wrapper
  language: python
  types: [python]
  additional_dependencies: ['pydocstyle']
- id: spelling
  name: spelling
  description: 'Spellcheck with Aspell'
  entry: spelling
  language: python
  types: [text]
  exclude_types: [binary]
